CREATE TABLE IF NOT EXISTS USERS (
  ID int NOT NULL AUTO_INCREMENT,
  USER_ID varchar(45) NOT NULL,
  USER_PW varchar(100) NOT NULL,
  USER_NAME varchar(45) NOT NULL,
  USER_EMAIL varchar(45) NOT NULL,
  ENABLED tinyint NOT NULL DEFAULT '1',
  REG_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MOD_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY USERID_UNIQUE (USER_ID),
  KEY FK_USERID (USER_ID)
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
  USER_ID varchar(45) NOT NULL,
  AUTHORITY varchar(45) NOT NULL DEFAULT 'USER',
  PRIMARY KEY (USER_ID)
);

ALTER TABLE AUTHORITIES ADD CONSTRAINT FK_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE;